-- Public-source POC inventory snapshot.
-- Data comes from live dealer, Capital One Auto Navigator, CARFAX, and marketplace listing pages researched on 2026-07-01.
-- Source links are stored per row; local images under client/public/vehicles keep demos stable without hotlinking.

DELETE FROM vehicles;

INSERT OR REPLACE INTO vehicles (
  id, vin, condition, year, make, model, trim, body_type, drive_type, fuel_type,
  transmission, engine, horsepower, mpg_city, mpg_highway, seats, doors, mileage,
  price, msrp, exterior_color, interior_color, description, key_features,
  use_case_tags, priority_tags, image_url, dealer_name, dealer_zip, source_name,
  source_url, in_stock, featured, last_updated_at
) VALUES
('used-honda-crv-exl-2023-mayfield','2HKRS4H75PH406069','used',2023,'Honda','CR-V','EX-L','suv','awd','gasoline','CVT','1.5L Turbo I4',190,27,32,5,4,77835,24348,NULL,'Black','Black','Public dealer listing snapshot for a 2023 Honda CR-V EX-L with AWD, leather seating, moonroof, heated seats, adaptive cruise control, Apple CarPlay, Android Auto, and dealer-disclosed CARFAX One-Owner / Clean CARFAX messaging.','["CARFAX One-Owner","Clean CARFAX","Leather seats","AWD","Adaptive cruise control","Moonroof","Heated seats","Apple CarPlay / Android Auto"]','["family","commuter","adventure"]','["safety","reliability","tech","cargo"]','/vehicles/honda-crv-exl.jpg','Ken Ganley Nissan Mayfield','44124','Mayfield Nissan public listing','https://www.mayfieldnissan.com/used-Mayfield%2BHeights-2023-Honda-CR%2BV-EX%2BL-2HKRS4H75PH406069',1,1,'2026-07-01T00:00:00Z'),

('used-toyota-rav4-hybrid-xse-2024-dallas','JTME6RFVXRJ058863','used',2024,'Toyota','RAV4 Hybrid','XSE','suv','awd','hybrid','eCVT','2.5L I4 Hybrid',219,41,38,5,4,19917,38976,NULL,'Midnight Black Metallic','Black','Public North Dallas CDJR and Capital One listing snapshot for a 2024 Toyota RAV4 Hybrid XSE with AWD, strong hybrid fuel economy, remote start, heated seats, heated steering wheel, power liftgate, blind spot monitor, and CARFAX 1-Owner / Good Value messaging.','["CARFAX 1-Owner","Good Value Badge","39 MPG combined","AWD hybrid system","Remote start","Heated seats","Heated steering wheel","Power liftgate","Blind spot monitor"]','["family","commuter","eco"]','["fuel-economy","safety","reliability","tech"]','/vehicles/toyota-rav4-hybrid-xse.jpg','North Dallas CDJR','75230','North Dallas CDJR + Capital One Auto Navigator','https://www.northdallascdjr.com/used/Toyota/2024-Toyota-RAV4-Hybrid-ce62f020ac184afd0b43bb2a3725420d.htm',1,1,'2026-07-01T00:00:00Z'),

('used-toyota-prius-le-2023-carfax','JTDACAAU1P3005638','used',2023,'Toyota','Prius','LE','hatchback','fwd','hybrid','Automatic','2.0L I4 Hybrid',194,57,56,5,4,40361,26548,NULL,'Blue','Black','CARFAX public listing snapshot for a 2023 Toyota Prius LE hatchback in Saint Louis. The listing calls out 57 city / 56 highway MPG, no accident or damage reported, personal use, CARFAX 1-Owner history, 10 service records, blind spot monitor, smart key, LED lights, lane departure warning, and heated mirrors.','["No accident or damage reported","CARFAX 1-Owner","10 service records","57 city / 56 highway MPG","Blind spot monitor","Smart key","Lane departure warning","LED lights"]','["commuter","eco","family"]','["fuel-economy","reliability","safety","value"]','/vehicles/toyota-prius-le.jpg','Dave Mungenast St Louis Honda','63110','CARFAX public search result','https://www.carfax.com/Used-2023-Toyota-Prius_z39336',1,1,'2026-07-01T00:00:00Z'),

('used-toyota-corolla-hybrid-le-2023-stg','JTDBCMFE2PJ014934','used',2023,'Toyota','Corolla Hybrid','LE','sedan','fwd','hybrid','1-Speed CVT w/OD','Gas/Electric I4 1.8L',138,53,46,5,4,49541,21135,NULL,'Ice Cap','Gray','STG Auto Group public listing snapshot for a 2023 Toyota Corolla Hybrid LE sedan. The listing shows 49,541 miles, FWD, 53 city / 46 highway MPG, adaptive cruise control, Apple CarPlay, Android Auto, automatic climate control, backup camera, collision warning, lane departure warning, lane keep assist, and a CARFAX report link.','["53 city / 46 highway MPG","Adaptive cruise control","Apple CarPlay","Android Auto","Backup camera","Collision warning","Lane departure warning","Lane keep assist","CARFAX report link"]','["commuter","eco"]','["fuel-economy","reliability","safety","value"]','/vehicles/toyota-corolla-hybrid-le.webp','STG Auto Group Montclair','91763','STG Auto Group public listing','https://www.stgautogroup.com/inventory/2023-toyota-corolla-hybrid-le-JTDBCMFE2PJ014934',1,1,'2026-07-01T00:00:00Z'),

('used-toyota-prius-prime-xse-2024-carfax','JTDACACU0R3039943','used',2024,'Toyota','Prius Prime','XSE','hatchback','fwd','plug-in-hybrid','Automatic','2.0L I4 Plug-In Hybrid',220,50,47,5,4,15611,32793,NULL,'White','Black','Direct CARFAX vehicle page snapshot for a 2024 Toyota Prius Prime XSE in Arlington, Virginia. The page shows no accident or damage reported, personal use, CARFAX 1-Owner history, 15,611 miles, good value pricing, 50 city / 47 highway MPG, 13.6 kWh battery, navigation, keyless entry, heated seats, heated steering wheel, blind spot monitor, and alloy wheels.','["No accident or damage reported","CARFAX 1-Owner","Good Value","50 city / 47 highway MPG","13.6 kWh battery","Navigation","Heated seats","Heated steering wheel","Blind spot monitor"]','["commuter","eco","performance"]','["fuel-economy","tech","safety","value"]','/vehicles/toyota-prius-prime-xse.jpg','Koons Toyota Arlington','22207','CARFAX direct vehicle page','https://www.carfax.com/vehicle/JTDACACU0R3039943',1,1,'2026-07-01T00:00:00Z'),

('cpo-ford-f150-lariat-2022-marshall','1FTFW1E88NFA61050','cpo',2022,'Ford','F-150','Lariat','truck','4wd','gasoline','Automatic','3.5L EcoBoost V6',400,18,23,5,4,20450,47206,NULL,'Oxford White','Black w/Medium Dark Slate','Marshall Ford public listing snapshot for a Ford Blue Advantage Certified 2022 F-150 Lariat. The listing calls out a 139-point inspection, transferable warranty, vehicle history, and roadside assistance along with the 3.5L EcoBoost and 4WD capability.','["Ford Blue Advantage Certified","139-point inspection","Transferable warranty","Vehicle history report","Roadside assistance","3.5L EcoBoost","4WD","Leather-trimmed Lariat cabin"]','["commercial","adventure","family"]','["towing","cargo","reliability","performance"]','/vehicles/ford-f150-lariat.jpg','Marshall Ford Co.','39350','Marshall Ford public listing','https://www.marshallfordco.com/used-Philadelphia%2B-2022-Ford-F%2B150-LARIAT-1FTFW1E88NFA61050',1,1,'2026-07-01T00:00:00Z'),

('used-tesla-model3-base-2023-capitalone','5YJ3E1EA2PF553184','used',2023,'Tesla','Model 3','Base','sedan','rwd','electric','Automatic','Single Motor Electric',271,NULL,NULL,5,4,31498,23998,NULL,'White','Black','Capital One Auto Navigator and marketplace snapshot for a 2023 Tesla Model 3 Base sedan. Positioned as an affordable EV entry with touchscreen-first controls, driver-assistance capability, keyless access, and public vehicle-history availability.','["Electric sedan","History report available","Touchscreen controls","Autopilot-capable hardware","Keyless access","Supercharger network access","Low operating cost"]','["commuter","eco","performance"]','["tech","fuel-economy","performance"]','/vehicles/tesla-model3.jpg','Capital One listed dealer','33401','Capital One Auto Navigator','https://www.capitalone.com/cars/vehicle-details/2023/Tesla/Model%203/Base/5YJ3E1EA2PF553184',1,1,'2026-07-01T00:00:00Z'),

('used-subaru-outback-premium-2020-carfax','4S4BTACC5L3107801','used',2020,'Subaru','Outback','Premium','wagon','awd','gasoline','CVT','2.5L Boxer H4',182,26,33,5,4,110449,16499,NULL,'White','Black','CARFAX VIN detail page for a 2020 Subaru Outback Premium in Cleveland. The listing shows no accident or damage reported, personal use, CARFAX 1-Owner history, 16 service records, AWD, 26 city / 33 highway MPG, and a great-value price.','["No accident or damage reported","CARFAX 1-Owner","16 service records","Standard AWD","EyeSight driver assist","Raised wagon utility","Great Value"]','["adventure","family","commuter"]','["reliability","cargo","safety","fuel-economy","value"]','/vehicles/subaru-outback.jpg','Carface Auto Sales','44130','CARFAX VIN detail page','https://www.carfax.com/vehicle/4S4BTACC5L3107801',1,0,'2026-07-01T00:00:00Z'),

('used-ford-mustang-gt-premium-2021-capitalone','1FA6P8CF7M5148245','used',2021,'Ford','Mustang','GT Premium','coupe','rwd','gasoline','Automatic','5.0L Coyote V8',450,15,24,4,2,39998,39998,NULL,'Black','Black','Capital One Auto Navigator marketplace snapshot for a 2021 Ford Mustang GT Premium coupe. This gives the POC a real performance option with a V8, rear-wheel drive, premium cabin positioning, and external listing link.','["5.0L Coyote V8","GT Premium trim","Rear-wheel drive","Performance coupe","Premium interior","External listing link"]','["performance","commuter"]','["performance","luxury"]','/vehicles/ford-mustang-gt.jpg','Capital One listed dealer','75201','Capital One Auto Navigator','https://www.capitalone.com/cars/used-2021-ford-mustang/gt-premium-in-dallas-tx',1,1,'2026-07-01T00:00:00Z'),

('cpo-ford-f150-xlt-2024-marshall','1FTFW3LDXRFA48107','cpo',2024,'Ford','F-150','XLT','truck','4wd','hybrid','Automatic','3.5L PowerBoost Hybrid V6',430,NULL,NULL,5,4,46791,39999,39999,'Iconic Silver Metallic','Black','Marshall Ford certified-pre-owned inventory snapshot for a 2024 F-150 XLT with 4WD and a twin-turbo gas/electric 3.5L V6. This row supports work-truck and hybrid-truck guided-flow searches.','["Certified pre-owned inventory","4WD","Twin-turbo gas/electric V6","Full-size crew cab","Hybrid truck capability","Strong value under $40k"]','["commercial","adventure","family","eco"]','["towing","cargo","fuel-economy","reliability"]','/vehicles/ford-f150-lariat.jpg','Marshall Ford Co.','39350','Marshall Ford certified inventory','https://mymarshallfordco.com/inventory/cpo/ford/f-150',1,0,'2026-07-01T00:00:00Z'),

('cpo-ford-f150-lariat-2024-marshall','1FTFW5L84RKE22992','cpo',2024,'Ford','F-150','Lariat','truck','4wd','gasoline','Automatic','3.5L EcoBoost V6',400,NULL,NULL,5,4,39220,54876,NULL,'Carbonized Gray Metallic','Black','Marshall Ford certified-pre-owned inventory snapshot for a 2024 F-150 Lariat with 4WD, 3.5L twin-turbo gas V6, and premium-truck positioning. Useful for shoppers balancing towing capability and nicer cabin features.','["Certified pre-owned inventory","Lariat trim","4WD","3.5L EcoBoost","Premium truck cabin","Crew cab utility"]','["commercial","adventure","family"]','["towing","cargo","luxury","performance"]','/vehicles/ford-f150-lariat.jpg','Marshall Ford Co.','39350','Marshall Ford certified inventory','https://mymarshallfordco.com/inventory/cpo/ford/f-150',1,0,'2026-07-01T00:00:00Z'),

('cpo-ford-f150-platinum-2024-marshall','1FTFW7L80RFA19127','cpo',2024,'Ford','F-150','Platinum','truck','4wd','gasoline','Automatic','3.5L EcoBoost V6',400,NULL,NULL,5,4,35707,59913,66500,'Star White Metallic Tri-Coat','Black','Marshall Ford certified-pre-owned inventory snapshot for a 2024 F-150 Platinum with 4WD, low mileage for the model year, and luxury-truck positioning. Best used when the shopper values comfort plus towing capability.','["Certified pre-owned inventory","Platinum trim","4WD","Luxury truck cabin","Crew cab utility","Premium paint"]','["commercial","adventure","family"]','["towing","cargo","luxury","tech"]','/vehicles/ford-f150-lariat.jpg','Marshall Ford Co.','39350','Marshall Ford certified inventory','https://mymarshallfordco.com/inventory/cpo/ford/f-150',1,0,'2026-07-01T00:00:00Z'),

('cpo-honda-crv-ex-2023-carfax','5J6RS4H44PL010243','cpo',2023,'Honda','CR-V','EX','suv','awd','gasoline','CVT','1.5L Turbo I4',190,27,32,5,4,39152,26594,NULL,'Urban Gray Pearl','Black','CARFAX public search snapshot for a certified 2023 Honda CR-V EX AWD with no accident or damage reported in the listing snippet. This adds a lower-mile CR-V alternative below $30k.','["Certified pre-owned listing","No accident or damage reported","AWD","Honda Sensing","Turbocharged 1.5L engine","Family-friendly cargo space"]','["family","commuter","adventure"]','["safety","reliability","cargo"]','/vehicles/honda-crv-exl.jpg','CARFAX listed dealer','44107','CARFAX public search result','https://www.carfax.com/Used-2023-Honda-CR-V-EX_x51862',1,0,'2026-07-01T00:00:00Z'),

('cpo-honda-crv-exl-2023-carfax','7FARS3H78PE006424','cpo',2023,'Honda','CR-V','EX-L','suv','fwd','gasoline','CVT','1.5L Turbo I4',190,28,34,5,4,23154,29757,NULL,'Platinum White Pearl','Black','CARFAX public search snapshot for a certified 2023 Honda CR-V EX-L FWD with no accident or damage reported in the listing snippet. A good fit for shoppers who want leather and lower mileage under $30k.','["Certified pre-owned listing","No accident or damage reported","Leather seats","Honda Sensing","Lower mileage","Efficient FWD setup"]','["family","commuter"]','["safety","reliability","fuel-economy","tech"]','/vehicles/honda-crv-exl.jpg','CARFAX listed dealer','33064','CARFAX public search result','https://www.carfax.com/Used-2023-Honda-CR-V_z39159',1,0,'2026-07-01T00:00:00Z'),

('used-toyota-rav4-le-2024-carfax','2T3H1RFV9RC276419','used',2024,'Toyota','RAV4','LE','suv','fwd','gasoline','Automatic','2.5L I4',203,27,35,5,4,27249,30101,NULL,'Silver Sky Metallic','Black','CARFAX public search snapshot for a 2024 Toyota RAV4 LE with 27,249 miles. This adds a newer non-hybrid Toyota SUV option around $30k for reliability-first shoppers.','["CARFAX listing snapshot","Toyota Safety Sense","Newer model year","Efficient 2.5L engine","Compact SUV utility","Reliability-focused option"]','["family","commuter"]','["reliability","safety","fuel-economy","cargo"]','/vehicles/toyota-rav4-hybrid-xse.jpg','CARFAX listed dealer','33064','CARFAX public search result','https://www.carfax.com/Used-2024-Toyota-RAV4-LE_x53329',1,0,'2026-07-01T00:00:00Z'),

('used-kia-telluride-s-2023-carfax','5XYP6DGCXPG388265','used',2023,'Kia','Telluride','S','suv','awd','gasoline','Automatic','3.8L V6',291,18,24,7,4,19330,32096,NULL,'Ebony Black','Black','CARFAX public search snapshot for a 2023 Kia Telluride S near Strongsville, Ohio with no accident or damage reported in the snippet and service history called out through 19,347 miles.','["No accident or damage reported","Three-row SUV","Low mileage for year","AWD","3.8L V6","Service-history snippet available"]','["family","adventure"]','["cargo","safety","reliability"]','/vehicles/kia-telluride-s.jpg','CARFAX listed dealer','44136','CARFAX public search result','https://www.carfax.com/Used-Cars-in-Lakewood-OH_c9632',1,0,'2026-07-01T00:00:00Z'),

('used-chevrolet-trax-rs-2026-carfax','KL77LJEP2TC031090','cpo',2026,'Chevrolet','Trax','RS 2RS','suv','fwd','gasoline','Automatic','1.2L Turbo I3',137,28,32,5,4,1290,25893,NULL,'Summit White','Jet Black','CARFAX public search snapshot for a certified used 2026 Chevrolet Trax RS 2RS with only 1,290 miles and no accident or damage reported in the listing snippet. Strong budget-friendly compact SUV option.','["Certified used listing","No accident or damage reported","Very low mileage","Compact SUV","Turbo engine","Budget-friendly newer model"]','["commuter","family"]','["tech","fuel-economy","safety","value"]','/vehicles/chevrolet-trax-2rs.jpg','CARFAX listed dealer','44060','CARFAX public search result','https://www.carfax.com/Used-Cars-in-Chesterland-OH_c24674',1,0,'2026-07-01T00:00:00Z'),

('used-kia-k5-gtline-2022-carfax','5XXG64J26NG157879','used',2022,'Kia','K5','GT-Line','sedan','fwd','gasoline','Automatic','1.6L Turbo I4',180,27,37,5,4,49801,22504,NULL,'Wolf Gray','Black','CARFAX public search snapshot for a 2022 Kia K5 GT-Line in the Cleveland area with no accident or damage reported and service history called out around 49,807 miles. Adds a sporty sedan option under $25k.','["No accident or damage reported","GT-Line styling","Turbo engine","Apple CarPlay / Android Auto","Driver-assistance tech","Sedan value under $25k"]','["commuter","performance"]','["tech","fuel-economy","value"]','/vehicles/kia-k5-gtline.jpg','CARFAX listed dealer','44124','CARFAX public search result','https://www.carfax.com/Used-Cars-in-Chesterland-OH_c24674',1,0,'2026-07-01T00:00:00Z'),

('used-mazda-cx30-s-2023-carfax','3MVDMBDM1PM514489','used',2023,'Mazda','CX-30','S Premium','suv','awd','gasoline','Automatic','2.5L I4',191,26,33,5,4,22228,23717,NULL,'Deep Crystal Blue Mica','Black','CARFAX VIN detail page for a 2023 Mazda CX-30 S Premium in Bedford, Ohio. The listing shows no accident or damage reported, personal use, CARFAX 1-Owner history, service at 22,224 miles, AWD, 26 city / 33 highway MPG, navigation, leather seats, heated seats, power liftgate, 18-inch wheels, and Bose sound.','["No accident or damage reported","CARFAX 1-Owner","AWD","Low mileage","Premium Package","Navigation","Leather seats","Heated seats","Bose sound system"]','["commuter","adventure"]','["safety","fuel-economy","tech","value"]','/vehicles/mazda-cx30.jpg','CARFAX listed dealer','44146','CARFAX VIN detail page','https://www.carfax.com/vehicle/3MVDMBDM1PM514489',1,0,'2026-07-01T00:00:00Z'),

('used-honda-odyssey-exl-2022-carfax','5FNRL6H73NB050130','used',2022,'Honda','Odyssey','EX-L','minivan','fwd','gasoline','Automatic','3.5L V6',280,19,28,8,4,84889,28697,NULL,'Black','Black','CARFAX public search snapshot for a 2022 Honda Odyssey EX-L minivan in Waite Park, Minnesota. The listing snippet advertised no accident or damage reported, CARFAX 1-Owner, 11 service records, leather seats, heated seats, power liftgate, blind spot monitor, and alloy wheels.','["No accident or damage reported","CARFAX 1-Owner","11 service records","Leather seats","Heated seats","Power liftgate","Blind spot monitor","8-passenger family space"]','["family","commuter"]','["cargo","safety","reliability","comfort"]','/vehicles/honda-odyssey-exl.jpg','Luther Honda of Saint Cloud','56387','CARFAX public search result','https://www.carfax.com/Used-2022-Honda-Odyssey_z38266',1,0,'2026-07-01T00:00:00Z'),

('used-lexus-rx350-2023-carfax','2T2BAMCA5PC024193','used',2023,'Lexus','RX 350','Base','suv','awd','gasoline','Automatic','2.4L Turbo I4',275,21,28,5,4,22040,49170,NULL,'Black','Black','CARFAX listing snapshot for a 2023 Lexus RX 350 AWD in Lynbrook, New York. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, three service records, remote start, navigation, heated seats, power liftgate, blind spot monitor, and alloy wheels.','["No accident or damage reported","CARFAX 1-Owner","Great Value","AWD","Remote start","Navigation","Heated seats","Power liftgate","Blind spot monitor"]','["family","commuter"]','["luxury","safety","tech","reliability"]','/vehicles/lexus-rx-350.jpg','Infiniti of Lynbrook',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Lexus-RX-350_x52091',1,1,'2026-07-01T00:00:00Z'),

('used-bmw-x5-xdrive40i-2022-carfax','5UXCR6C09N9N13136','used',2022,'BMW','X5','xDrive40i','suv','awd','gasoline','Automatic','3.0L Turbo I6',335,21,25,5,4,82047,31733,NULL,'Black','Black','CARFAX listing snapshot for a 2022 BMW X5 xDrive40i in Visalia, California. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 16 service records, M Sport Package, Driver Assistance Package, remote start, navigation, trailer hitch, leather seats, and heated seats.','["No accident or damage reported","CARFAX 1-Owner","16 service records","M Sport Package","Driver Assistance Package","Remote start","Navigation","Leather seats","Trailer hitch"]','["family","commuter","performance"]','["luxury","tech","performance","safety"]','/vehicles/bmw-x5-xdrive40i.jpg','Giant Chevrolet Cadillac',NULL,'CARFAX public search result','https://www.carfax.com/Used-2022-BMW-X5-xDrive40i_x49521',1,1,'2026-07-01T00:00:00Z'),

('used-mercedes-glc300-2024-carfax','W1NKM4HB4RF205060','used',2024,'Mercedes-Benz','GLC','300','suv','awd','gasoline','Automatic','2.0L Turbo I4',255,24,32,5,4,11264,41978,NULL,'White','Black','CARFAX Los Angeles listing snapshot for a 2024 Mercedes-Benz GLC 300. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, three service records, AWD, remote start, heated seats, power liftgate, blind spot monitor, cargo cover, and dual exhaust.','["No accident or damage reported","CARFAX 1-Owner","Great Value","AWD","Remote start","Heated seats","Power liftgate","Blind spot monitor","Cargo cover"]','["family","commuter"]','["luxury","tech","safety","reliability"]','/vehicles/mercedes-glc-300.jpg','Mercedes-Benz of Beverly Hills',NULL,'CARFAX public search result','https://www.carfax.com/Used-Mercedes-Benz-GLC-Los-Angeles-CA_w470_c4914',1,1,'2026-07-01T00:00:00Z'),

('used-audi-q5-premium-plus-2023-carfax','WA1EAAFY3P2103671','used',2023,'Audi','Q5','Premium Plus 45','suv','awd','gasoline','Automatic','2.0L Turbo I4',261,22,29,5,4,30998,30795,NULL,'White','Black','CARFAX VIN detail page for a 2023 Audi Q5 Premium Plus 45 in Summerville, South Carolina. The listing shows no accident or damage reported, personal use, CARFAX 1-Owner history, eight service records, AWD, 22 city / 29 highway MPG, Convenience Package, Premium Plus Package, S-Line Package, leather seats, heated seats, and roof rack.','["No accident or damage reported","CARFAX 1-Owner","AWD","Premium Plus trim","S-Line Package","Convenience Package","Leather seats","Heated seats","Great Value"]','["family","commuter"]','["luxury","tech","safety","fuel-economy","value"]','/vehicles/audi-q5-premium-plus.jpg','Automaxx of the Carolinas',NULL,'CARFAX VIN detail page','https://www.carfax.com/vehicle/WA1EAAFY3P2103671',1,0,'2026-07-01T00:00:00Z'),

('used-genesis-gv70-2023-carfax','KMUMADTB3PU090683','used',2023,'Genesis','GV70','2.5T','suv','awd','gasoline','Automatic','2.5L Turbo I4',300,NULL,NULL,5,4,45938,34085,NULL,'White','Black','CARFAX listing snapshot for a 2023 Genesis GV70 in La Quinta, California. The listing showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, nine service records, AWD, cargo package, remote start, navigation, leather seats, heated seats, heated steering wheel, ambient lighting, and power liftgate.','["No accident or damage reported","CARFAX 1-Owner","Great Value","AWD","Remote start","Navigation","Leather seats","Heated steering wheel","Power liftgate"]','["family","commuter","performance"]','["luxury","tech","performance","safety"]','/vehicles/genesis-gv70.jpg','Hyundai of La Quinta',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Genesis-GV70_z38958',1,0,'2026-07-01T00:00:00Z'),

('cpo-hyundai-ioniq5-sel-2023-carfax','KM8KN4AE3PU185476','cpo',2023,'Hyundai','Ioniq 5','SEL','suv','rwd','electric','Automatic','Electric',225,NULL,NULL,5,4,41515,24075,NULL,'Blue','Black','CARFAX listing snapshot for a certified 2023 Hyundai Ioniq 5 SEL in Stockton, California. The listing showed great-value pricing, electric powertrain, rear-wheel drive, CARFAX 1-Owner history, driver assistance package, navigation, leather seats, heated seats, heated steering wheel, power liftgate, blind spot monitor, smart key, and LED lights.','["Certified pre-owned listing","CARFAX 1-Owner","Great Value","Electric SUV","Rear-wheel drive","Driver Assistance Package","Navigation","Heated seats","Power liftgate","Blind spot monitor"]','["commuter","eco","family"]','["fuel-economy","tech","safety","value"]','/vehicles/hyundai-ioniq5.jpg','Stockton Hyundai',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Hyundai-Ioniq-5_z39091',1,1,'2026-07-01T00:00:00Z'),

('cpo-kia-ev6-wind-2023-carfax','KNDC34LA3P5603232','cpo',2023,'Kia','EV6','Wind','suv','rwd','electric','Automatic','Electric',225,134,101,5,4,17282,25391,NULL,'Red','Black','CARFAX listing snapshot for a certified 2023 Kia EV6 Wind in Fort Myers, Florida. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 10 service records, 134 city / 101 highway MPGe, rear-wheel drive, Technology Package, remote start, navigation, leather seats, heated seats, power liftgate, blind spot monitor, and 19 inch wheels.','["No accident or damage reported","Certified pre-owned listing","CARFAX 1-Owner","134 city / 101 highway MPGe","Technology Package","Remote start","Navigation","Heated seats","Power liftgate","Blind spot monitor"]','["commuter","eco","family"]','["fuel-economy","tech","safety","value"]','/vehicles/kia-ev6-wind.jpg','Kia of Fort Myers',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Kia-EV6-Wind_x52126',1,1,'2026-07-01T00:00:00Z'),

('used-tesla-model-y-long-range-2023-carfax','7SAYGDEE8PA140089','used',2023,'Tesla','Model Y','Long Range','suv','awd','electric','Automatic','Dual Motor Electric',425,127,117,5,4,53099,31415,NULL,'White','Black','CARFAX listing snapshot for a 2023 Tesla Model Y Long Range in Corinth, Mississippi. The listing showed great-value pricing, CARFAX 1-Owner history, 127 city / 117 highway MPGe, AWD, navigation, keyless entry, leather seats, heated seats, heated steering wheel, power liftgate, blind spot monitor, smart key, lane departure warning, and rear heated seats.','["CARFAX 1-Owner","127 city / 117 highway MPGe","AWD electric SUV","Navigation","Leather seats","Heated seats","Power liftgate","Blind spot monitor","Rear heated seats"]','["commuter","eco","family","performance"]','["fuel-economy","tech","performance","safety"]','/vehicles/tesla-model-y.jpg','Ford of Corinth',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Tesla-Model-Y-Long-Range_x52070',1,1,'2026-07-01T00:00:00Z'),

('cpo-chevrolet-bolt-euv-premier-2023-carfax','1G1FZ6S0XP4162679','cpo',2023,'Chevrolet','Bolt EUV','Premier','suv','fwd','electric','Automatic','Electric',200,125,104,5,4,12642,22475,NULL,'White','Black','CARFAX listing snapshot for a certified 2023 Chevrolet Bolt EUV Premier in Oak Lawn, Illinois. The page showed great-value pricing, 125 city / 104 highway MPGe, electric powertrain, front-wheel drive, CARFAX 1-Owner history, eight service records, navigation, Bose sound system, and satellite radio.','["Certified pre-owned listing","CARFAX 1-Owner","125 city / 104 highway MPGe","Electric compact SUV","Navigation","Bose sound system","Satellite radio","Low mileage"]','["commuter","eco","family"]','["fuel-economy","tech","value","safety"]','/vehicles/chevrolet-bolt-euv.jpg','Mike Haggerty Buick GMC',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Chevrolet-Bolt-EUV-Premier_x51427',1,0,'2026-07-01T00:00:00Z'),

('used-nissan-leaf-s-2023-carfax','1N4AZ1BV5PC562869','used',2023,'Nissan','Leaf','S','hatchback','fwd','electric','Automatic','Electric',147,123,99,5,4,17670,14680,NULL,'Silver','Black','CARFAX listing snapshot for a 2023 Nissan Leaf S in Warren, Michigan. The listing showed great-value pricing, no accident or damage reported, 123 city / 99 highway MPGe, electric powertrain, front-wheel drive, keyless entry, spoiler, splash guards, satellite radio, 16 inch wheels, NissanConnect, cloth seats, and independent suspension.','["No accident or damage reported","Great Value","123 city / 99 highway MPGe","Electric hatchback","Keyless entry","NissanConnect","Satellite radio","Low running costs"]','["commuter","eco"]','["fuel-economy","value","tech","reliability"]','/vehicles/nissan-leaf.jpg','Golling Toyota of Warren',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Nissan-Leaf_z38920',1,0,'2026-07-01T00:00:00Z'),

('used-ford-f150-lightning-xlt-2023-carfax','1FTVW1EL5PWG23375','used',2023,'Ford','F-150 Lightning','XLT','truck','awd','electric','Automatic','Dual Motor Electric',452,76,61,5,4,32375,37600,NULL,'Blue','Black','CARFAX listing snapshot for a 2023 Ford F-150 Lightning XLT in Memphis, Tennessee. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, five service records, 76 city / 61 highway MPGe, electric pickup body style, AWD, heated seats, and 20 inch wheels.','["No accident or damage reported","CARFAX 1-Owner","76 city / 61 highway MPGe","Electric pickup","AWD","Heated seats","20 inch wheels","Work-truck utility"]','["commercial","eco","adventure","family"]','["towing","cargo","fuel-economy","tech"]','/vehicles/ford-f150-lightning.jpg','Rivard-Royall GMC',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Ford-F-150-Lightning_z39219',1,1,'2026-07-01T00:00:00Z'),

('used-rivian-r1t-adventure-2023-carfax','7FCTGAAA6PN024171','used',2023,'Rivian','R1T','Adventure','truck','awd','electric','Automatic','Quad Motor Electric',835,NULL,NULL,5,4,12249,58794,NULL,'Silver','Black','CARFAX New York market listing snapshot for a 2023 Rivian R1T Adventure in Wall Township, New Jersey. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, electric pickup body style, AWD, navigation, air suspension, fog lights, leather seats, heated seats, blind spot monitor, alloy wheels, LED lights, and parking sensors.','["No accident or damage reported","CARFAX 1-Owner","Electric pickup","AWD","Air suspension","Navigation","Leather seats","Heated seats","Blind spot monitor","Parking sensors"]','["adventure","commercial","eco","performance"]','["performance","towing","tech","luxury"]','/vehicles/rivian-r1t.jpg','Automotive Avenues',NULL,'CARFAX public search result','https://www.carfax.com/Used-Rivian-R1T-New-York-NY_w10263_c8636',1,0,'2026-07-01T00:00:00Z'),

('cpo-hyundai-elantra-limited-2024-carfax','KMHLN4DJ3RU099326','cpo',2024,'Hyundai','Elantra','Limited Edition','sedan','fwd','hybrid','Automatic','1.6L I4 Hybrid',139,49,52,5,4,20465,25020,NULL,'Gray','Black','CARFAX listing snapshot for a certified 2024 Hyundai Elantra Limited Edition hybrid in Cookeville, Tennessee. The listing showed good-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, five service records, 49 city / 52 highway MPG, front-wheel drive, navigation, keyless entry, leather seats, heated seats, alloy wheels, ventilated seats, heated mirrors, satellite radio, and seat memory.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","49 city / 52 highway MPG","Hybrid sedan","Navigation","Leather seats","Heated seats","Ventilated seats"]','["commuter","eco"]','["fuel-economy","value","tech","safety"]','/vehicles/hyundai-elantra.jpg','Hyundai of Cookeville',NULL,'CARFAX public search result','https://www.carfax.com/Used-2024-Hyundai-Elantra_z39702',1,1,'2026-07-01T00:00:00Z'),

('used-nissan-altima-sr-2023-carfax','1N4BL4CV7PN382075','used',2023,'Nissan','Altima','SR','sedan','fwd','gasoline','Automatic','2.5L I4',188,27,38,5,4,31385,22866,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Nissan Altima SR sedan. The page showed no accident or damage reported, personal use, CARFAX 1-Owner history, front-wheel drive, 27 city / 38 highway MPG, premium package, keyless entry, leather seats, heated seats, blind spot monitor, 19 inch wheels, alloy wheels, splash guards, satellite radio, and sport seats.','["No accident or damage reported","CARFAX 1-Owner","27 city / 38 highway MPG","Premium Package","Keyless entry","Leather seats","Heated seats","Blind spot monitor","Sport seats"]','["commuter","family"]','["fuel-economy","value","safety","tech"]','/vehicles/kia-k5-gtline.jpg','Beaman Dodge Chrysler Jeep Ram FIAT',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Nissan-Altima-SR_x51423',1,0,'2026-07-01T00:00:00Z'),

('used-volkswagen-gti-40th-2023-carfax','WVW8A7CD0PW196052','used',2023,'Volkswagen','GTI','40th Anniversary Edition','hatchback','fwd','gasoline','Automatic','2.0L Turbo I4',241,24,34,5,4,11011,29036,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Volkswagen GTI 40th Anniversary Edition in Tracy, California. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, four service records, 24 city / 34 highway MPG, keyless entry, fog lights, spoiler, heated seats, heated steering wheel, 19 inch wheels, alloy wheels, lane departure warning, and sport seats.','["No accident or damage reported","CARFAX 1-Owner","Great Value","24 city / 34 highway MPG","Heated seats","Heated steering wheel","19 inch wheels","Sport seats","Lane departure warning"]','["commuter","performance"]','["performance","tech","fuel-economy","value"]','/vehicles/volkswagen-gti.jpg','Tracy Volkswagen',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Volkswagen-GTI_z39118',1,0,'2026-07-01T00:00:00Z'),

('used-acura-integra-aspec-tech-2024-carfax','19UDE4H67RA002159','used',2024,'Acura','Integra','A-Spec Technology','hatchback','fwd','gasoline','Automatic','1.5L Turbo I4',200,30,37,5,4,35217,29636,NULL,'White','Black','CARFAX listing snapshot for a 2024 Acura Integra A-Spec Technology in Greenacres, Florida. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, five service records, 30 city / 37 highway MPG, Technology Package, A-Spec Package, keyless entry, fog lights, leather seats, heated seats, 18 inch wheels, alloy wheels, and lane departure warning.','["No accident or damage reported","CARFAX 1-Owner","Great Value","30 city / 37 highway MPG","Technology Package","A-Spec Package","Leather seats","Heated seats","Lane departure warning"]','["commuter","performance"]','["tech","performance","fuel-economy","safety"]','/vehicles/acura-integra-aspec.jpg','Greenacres Nissan',NULL,'CARFAX public search result','https://www.carfax.com/Used-2024-Acura-Integra_z39420',1,0,'2026-07-01T00:00:00Z'),

('used-bmw-330i-2023-carfax','3MW69FF08P8D54520','used',2023,'BMW','3 Series','330i','sedan','rwd','gasoline','Automatic','2.0L Turbo I4',255,25,34,5,4,26330,33538,NULL,'White','Black','CARFAX listing snapshot for a 2023 BMW 330i sedan in Seaside, California. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, three service records, 25 city / 34 highway MPG, Premium Package, Driver Assistance Package, remote start, navigation, heated seats, heated steering wheel, blind spot monitor, and 19 inch wheels.','["No accident or damage reported","CARFAX 1-Owner","Great Value","25 city / 34 highway MPG","Premium Package","Driver Assistance Package","Remote start","Navigation","Blind spot monitor"]','["commuter","performance"]','["luxury","performance","tech","fuel-economy"]','/vehicles/bmw-330i.jpg','BMW of Monterey',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-BMW-3-Series-330i_x51088',1,0,'2026-07-01T00:00:00Z'),

('cpo-mercedes-c300-2023-carfax','W1KAF4HB6PR146589','cpo',2023,'Mercedes-Benz','C-Class','C 300','sedan','awd','gasoline','Automatic','2.0L Turbo I4',255,24,33,5,4,15018,37298,NULL,'Gray','Black','CARFAX listing snapshot for a certified 2023 Mercedes-Benz C 300 sedan in Westminster, Colorado. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, seven service records, 24 city / 33 highway MPG, AWD, Night Package, keyless entry, heated seats, 18 inch wheels, alloy wheels, heated mirrors, seat memory, premium sound system, and sport suspension.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","24 city / 33 highway MPG","AWD","Night Package","Heated seats","Premium sound system","Sport suspension"]','["commuter","performance"]','["luxury","tech","performance","safety"]','/vehicles/mercedes-c300.jpg','Mercedes-Benz of Westminster',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Mercedes-Benz-C-Class-C-300_x51393',1,0,'2026-07-01T00:00:00Z'),

('used-audi-a4-premium-plus-2023-carfax','WAUEAAF48PN003581','used',2023,'Audi','A4','Premium Plus 45','sedan','awd','gasoline','Automatic','2.0L Turbo I4',261,24,32,5,4,18017,31993,NULL,'White','Black','CARFAX listing snapshot for a 2023 Audi A4 Premium Plus 45 sedan in Roswell, Georgia. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, five service records, 24 city / 32 highway MPG, AWD, Convenience Package, S-Line Package, keyless entry, fog lights, heated steering wheel, blind spot monitor, parking sensors, and satellite radio.','["No accident or damage reported","CARFAX 1-Owner","Great Value","24 city / 32 highway MPG","AWD","Premium Plus","S-Line Package","Blind spot monitor","Parking sensors"]','["commuter","performance"]','["luxury","tech","safety","fuel-economy"]','/vehicles/audi-a4-premium-plus.jpg','Roswell Infiniti of North Atlanta',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Audi-A4-Premium-Plus_x51494',1,0,'2026-07-01T00:00:00Z'),

('used-chevrolet-silverado-rst-2023-carfax','2GCUDEED0P1114139','used',2023,'Chevrolet','Silverado 1500','RST','truck','4wd','gasoline','Automatic','5.3L V8',355,15,19,5,4,96279,34995,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Chevrolet Silverado 1500 RST in Caro, Michigan. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 20 service records, 15 city / 19 highway MPG, 4WD, convenience package, leather package, protection package, remote start, navigation, keyless entry, fog lights, and trailer hitch.','["No accident or damage reported","CARFAX 1-Owner","20 service records","4WD","5.3L V8","Remote start","Navigation","Trailer hitch","Protection Package"]','["commercial","adventure","family"]','["towing","cargo","performance","reliability"]','/vehicles/chevrolet-silverado-1500.jpg','Pat Curtis Chevrolet',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Chevrolet-Silverado-1500_z39212',1,0,'2026-07-01T00:00:00Z'),

('cpo-gmc-sierra-denali-2023-carfax','1GTUUGEDXPZ125426','cpo',2023,'GMC','Sierra 1500','Denali','truck','4wd','gasoline','Automatic','5.3L V8',355,15,19,5,4,58753,48533,NULL,'White','Black','CARFAX listing snapshot for a certified 2023 GMC Sierra 1500 Denali in Cranbury, New Jersey. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 13 service records, 15 city / 19 highway MPG, 4WD, leather-heavy Denali positioning, navigation, remote start, running boards, ventilated seats, Bose sound system, and trailer brake controller availability in the filter set.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","Denali trim","4WD","Navigation","Remote start","Ventilated seats","Bose sound system"]','["commercial","family","adventure"]','["luxury","towing","cargo","tech"]','/vehicles/gmc-sierra-denali.jpg','T & T Coast GMC',NULL,'CARFAX public search result','https://www.carfax.com/Used-GMC-Sierra-1500-Denali_t7672',1,0,'2026-07-01T00:00:00Z'),

('used-ram-1500-bighorn-2023-carfax','1C6SRFMT8PN525026','used',2023,'Ram','1500','Big Horn/Lone Star','truck','4wd','gasoline','Automatic','5.7L Hemi V8',395,17,22,5,4,110000,24594,NULL,'White','Black','CARFAX listing snapshot for a 2023 Ram 1500 Big Horn/Lone Star in La Junta, Colorado. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 10 service records, 4WD, 5.7L V8, protection package, remote start, navigation, keyless entry, fog lights, trailer hitch, heated seats, heated steering wheel, bucket seats, and skid plate.','["No accident or damage reported","CARFAX 1-Owner","10 service records","4WD","5.7L Hemi V8","Remote start","Navigation","Trailer hitch","Heated seats"]','["commercial","adventure","family"]','["towing","cargo","value","performance"]','/vehicles/ram-1500-bighorn.jpg','Perkins Chevrolet GMC',NULL,'CARFAX public search result','https://www.carfax.com/Used-Ram-1500_w589',1,0,'2026-07-01T00:00:00Z'),

('used-jeep-wrangler-rubicon-2023-carfax','1C4JJXFMXPW588145','used',2023,'Jeep','Wrangler','Rubicon','suv','4wd','diesel','Automatic','3.0L V6 Diesel',260,21,26,5,4,42672,37348,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Jeep Wrangler Rubicon in Arlington, Wisconsin. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, nine service records, 21 city / 26 highway MPG, 4WD, diesel engine, Cold Weather Package, navigation, keyless entry, fog lights, trailer hitch, leather seats, heated seats, trailer wiring, heated steering wheel, and bucket seats.','["No accident or damage reported","CARFAX 1-Owner","Rubicon trim","4WD","Diesel engine","Cold Weather Package","Navigation","Trailer hitch","Heated seats"]','["adventure","performance"]','["towing","performance","reliability","tech"]','/vehicles/jeep-wrangler-rubicon.jpg','Bell Ford',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Jeep-Wrangler_z38962',1,1,'2026-07-01T00:00:00Z'),

('used-toyota-sienna-xle-2023-carfax','5TDYRKEC6PS141802','used',2023,'Toyota','Sienna','XLE','minivan','fwd','hybrid','Automatic','2.5L I4 Hybrid',245,36,36,8,4,44057,40212,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Toyota Sienna XLE minivan in Dickinson, Texas. The page showed good-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, six service records, hybrid powertrain, 36 city / 36 highway MPG, front-wheel drive, heated seats, folding mirrors, power liftgate, blind spot monitor, bench seat, captains chairs, LED lights, third row seating, and lane departure warning.','["No accident or damage reported","CARFAX 1-Owner","Hybrid minivan","36 city / 36 highway MPG","Power liftgate","Blind spot monitor","Captains chairs","Third row seating","Lane departure warning"]','["family","commuter","eco"]','["cargo","fuel-economy","safety","reliability"]','/vehicles/toyota-sienna-xle.jpg','League City Chrysler Jeep Dodge Ram',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Toyota-Sienna-XLE_x51746',1,1,'2026-07-01T00:00:00Z'),

('used-chrysler-pacifica-touring-l-2023-carfax','2C4RC1BG5PR534710','used',2023,'Chrysler','Pacifica','Touring-L','minivan','fwd','gasoline','Automatic','3.6L V6',287,19,28,7,4,85482,19899,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 Chrysler Pacifica Touring-L in Germantown, Maryland. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, seven service records, 19 city / 28 highway MPG, front-wheel drive, keyless entry, fog lights, passenger van configuration, heated seats, heated steering wheel, bucket seats, power liftgate, wind deflector, and alloy wheels.','["No accident or damage reported","CARFAX 1-Owner","Great Value","19 city / 28 highway MPG","Passenger van configuration","Heated seats","Heated steering wheel","Power liftgate","Alloy wheels"]','["family","commuter"]','["cargo","value","safety","tech"]','/vehicles/chrysler-pacifica-touring-l.jpg','Criswell Nissan',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Chrysler-Pacifica_z39214',1,0,'2026-07-01T00:00:00Z'),

('cpo-volvo-v60-b5-plus-2025-carfax','YV4L12WKXS2149485','cpo',2025,'Volvo','V60','B5 Plus','wagon','awd','gasoline','Automatic','2.0L Turbo I4',247,24,31,5,4,18053,36495,NULL,'Silver','Black','CARFAX listing snapshot for a certified 2025 Volvo V60 B5 Plus wagon in Santa Ana, California. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, five service records, 24 city / 31 highway MPG, AWD, climate package, navigation, leather seats, heated seats, cargo cover, heated steering wheel, bucket seats, and blind spot monitor.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","24 city / 31 highway MPG","AWD wagon","Climate Package","Navigation","Leather seats","Blind spot monitor"]','["family","commuter","adventure"]','["safety","cargo","luxury","fuel-economy"]','/vehicles/volvo-v60.jpg','Volvo Cars Orange County',NULL,'CARFAX public search result','https://www.carfax.com/Used-Volvo-V60_w660',1,0,'2026-07-01T00:00:00Z'),

('cpo-subaru-outback-wilderness-2023-carfax','4S4BTGUD3P3211252','cpo',2023,'Subaru','Outback','Wilderness','wagon','awd','gasoline','Automatic','2.4L Turbo Boxer H4',260,21,26,5,4,61182,28115,NULL,'Gray','Black','CARFAX listing snapshot for a certified 2023 Subaru Outback Wilderness wagon in Stamford, Connecticut. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, 11 service records, 21 city / 26 highway MPG, AWD, Driver Assistance Package, roof rack, navigation, keyless entry, fog lights, spoiler, heated seats, power liftgate, alloy wheels, and paddle shifter.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","AWD Wilderness trim","Roof rack","Navigation","Heated seats","Power liftgate","Driver Assistance Package"]','["adventure","family","commuter"]','["cargo","safety","reliability","performance"]','/vehicles/subaru-outback-wilderness.jpg','Subaru Stamford',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Subaru-Outback-Wilderness_x51361',1,1,'2026-07-01T00:00:00Z'),

('used-ford-transit-xlt-2025-carfax','1FBAX2C86SKA45047','used',2025,'Ford','Transit','XLT','van','rwd','gasoline','Automatic','3.5L V6',275,NULL,NULL,12,3,6252,52209,NULL,'White','Gray','CARFAX listing snapshot for a 2025 Ford Transit XLT van in Saint Charles, Missouri. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, one service record, rear-wheel drive, 3.5L V6, passenger van configuration, medium roof, bucket seats, third row seating, lane departure warning, tow hooks, steel wheels, and rear air conditioning.','["No accident or damage reported","CARFAX 1-Owner","Passenger van configuration","Medium roof","Third row seating","Rear air conditioning","Lane departure warning","Tow hooks","Commercial shuttle use"]','["commercial","family"]','["cargo","safety","reliability","value"]','/vehicles/ford-transit-xlt.jpg','Pundmann Ford',NULL,'CARFAX public search result','https://www.carfax.com/Used-Ford-Transit_w249',1,0,'2026-07-01T00:00:00Z'),

('used-mercedes-sprinter2500-2022-carfax','W1Y4EDHYXNT106283','used',2022,'Mercedes-Benz','Sprinter 2500','High Roof','van','rwd','diesel','Automatic','3.0L V6 Diesel',188,NULL,NULL,2,3,93255,35375,NULL,'Gray','Gray','CARFAX listing snapshot for a 2022 Mercedes-Benz Sprinter 2500 High Roof van in Bay Shore, New York. The page showed good-value pricing, no accident or damage reported, corporate use, CARFAX 1-Owner history, eight service records, rear-wheel drive, 3.0L V6, high roof, extended van, keyless entry, heated mirrors, 16 inch steel wheels, cloth seats, and independent suspension.','["No accident or damage reported","CARFAX 1-Owner","Corporate use","High roof","Extended van","Diesel engine","Rear-wheel drive","Steel wheels","Commercial cargo platform"]','["commercial"]','["cargo","reliability","towing","value"]','/vehicles/mercedes-sprinter-2500.jpg','Newins Bay Shore Ford',NULL,'CARFAX public search result','https://www.carfax.com/Used-2022-Mercedes-Benz-Sprinter-2500_x50407',1,0,'2026-07-01T00:00:00Z'),

('cpo-mazda-miata-grand-touring-2023-carfax','JM1NDAD74P0559620','cpo',2023,'Mazda','MX-5 Miata','Grand Touring','convertible','rwd','gasoline','Automatic','2.0L I4',181,26,35,2,2,6240,29955,NULL,'White','Black','CARFAX listing snapshot for a certified 2023 Mazda MX-5 Miata Grand Touring in Erie, Pennsylvania. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, four service records, 26 city / 35 highway MPG, rear-wheel drive, navigation, leather seats, heated seats, bucket seats, blind spot monitor, alloy wheels, LED lights, lane departure warning, and premium sound system.','["Certified pre-owned listing","No accident or damage reported","CARFAX 1-Owner","26 city / 35 highway MPG","Rear-wheel drive","Navigation","Leather seats","Heated seats","Blind spot monitor"]','["performance","commuter"]','["performance","fuel-economy","tech","value"]','/vehicles/mazda-miata-grand-touring.jpg','Auto Express Mazda',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-Mazda-Miata_z39283',1,1,'2026-07-01T00:00:00Z'),

('used-bmw-430i-coupe-2023-carfax','WBA53AP02PCM82842','used',2023,'BMW','4 Series','430i Coupe','coupe','rwd','gasoline','Automatic','2.0L Turbo I4',255,25,34,4,2,19581,32787,NULL,'Gray','Black','CARFAX listing snapshot for a 2023 BMW 430i Coupe in Honolulu, Hawaii. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, two service records, 25 city / 34 highway MPG, rear-wheel drive, Convenience Package, navigation, keyless entry, 18 inch wheels, alloy wheels, heated mirrors, satellite radio, seat memory, premium sound system, and sport seats.','["No accident or damage reported","CARFAX 1-Owner","25 city / 34 highway MPG","Rear-wheel drive","Convenience Package","Navigation","Premium sound system","Sport seats","Alloy wheels"]','["performance","commuter"]','["performance","luxury","tech","fuel-economy"]','/vehicles/bmw-430i-coupe.jpg','Aloha Kia Airport',NULL,'CARFAX public search result','https://www.carfax.com/Used-2023-BMW-4-Series-430i_x50729',1,0,'2026-07-01T00:00:00Z'),

('used-dodge-challenger-rt-scat-pack-2023-carfax','2C3CDZFJ9PH630325','used',2023,'Dodge','Challenger','R/T Scat Pack','coupe','rwd','gasoline','Automatic','6.4L Hemi V8',485,15,24,5,2,8106,48124,NULL,'Black','Black','CARFAX listing snapshot for a 2023 Dodge Challenger R/T Scat Pack in Greenwood, Indiana. The page showed great-value pricing, no accident or damage reported, personal use, CARFAX 1-Owner history, one service record, 15 city / 24 highway MPG, rear-wheel drive, V8 engine, coupe body style, and high-demand listing status.','["No accident or damage reported","CARFAX 1-Owner","Great Value","R/T Scat Pack","6.4L Hemi V8","Rear-wheel drive","Low mileage","Performance coupe"]','["performance"]','["performance","value","luxury"]','/vehicles/dodge-challenger-rt.jpg','Hubler Mazda',NULL,'CARFAX public search result','https://www.carfax.com/Used-Dodge-Challenger_w194',1,0,'2026-07-01T00:00:00Z');
