-- 28 demo vehicles covering all body types, conditions, price ranges
-- Summit Ford vehicles tagged for Brand Concierge testing

INSERT OR REPLACE INTO vehicles (id,condition,year,make,model,trim,body_type,drive_type,fuel_type,transmission,engine,horsepower,mpg_city,mpg_highway,seats,mileage,price,msrp,exterior_color,description,key_features,use_case_tags,priority_tags,image_url,dealer_name,in_stock) VALUES
('suv-001','new',2024,'Honda','CR-V','EX-L','suv','awd','hybrid','cvt','2.0L Hybrid',204,43,36,5,0,37500,39200,'Sonic Gray Pearl','The 2024 CR-V Hybrid EX-L combines excellent fuel economy with a spacious, tech-forward interior. Standard AWD and a refined ride make it ideal for families and commuters alike.','["Honda Sensing Suite","Heated front seats","Apple CarPlay / Android Auto","Power tailgate","Lane keeping assist"]','["family","commuter","eco"]','["safety","fuel-economy","reliability"]',NULL,'Mountain Motors',1),

('suv-002','used',2022,'Toyota','RAV4','XLE Premium','suv','awd','gasoline','automatic','2.5L 4-cylinder',203,27,35,5,28400,31800,NULL,'Midnight Black','A well-maintained RAV4 XLE Premium with all the right options. AWD, a panoramic sunroof, and Toyota Safety Sense 2.0 make this a standout buy at its price point.','["Toyota Safety Sense 2.0","Panoramic moonroof","Heated front seats","8-inch touchscreen","Wireless charging"]','["family","commuter","adventure"]','["safety","reliability","cargo"]',NULL,'Mountain Motors',1),

('suv-003','new',2023,'Ford','Explorer','XLT','suv','4wd','gasoline','automatic','2.3L EcoBoost',300,21,28,7,0,45200,46800,'Star White Metallic','The Explorer XLT seats seven with third-row access, a powerful EcoBoost engine, and Ford Co-Pilot360. Perfect for growing families who need capability and space.','["Ford Co-Pilot360","Third-row seating","SYNC 4 with 13.2-inch screen","4WD with terrain modes","Trailer tow package"]','["family","adventure","commercial"]','["cargo","safety","towing"]',NULL,'Summit Ford',1),

('suv-004','used',2021,'Subaru','Outback','Limited XT','suv','awd','gasoline','cvt','2.4L Turbo',260,26,33,5,34200,28500,NULL,'Magnetite Gray','The Outback Limited XT punches above its weight with a turbocharged engine, standard AWD, and Subaru''s legendary reliability. Wagon versatility in an SUV package.','["EyeSight Driver Assist","11.6-inch touchscreen","Heated seats and steering wheel","Power rear gate","Roof rails"]','["adventure","commuter","family"]','["reliability","cargo","fuel-economy"]',NULL,'Mountain Motors',1),

('suv-005','new',2023,'Toyota','RAV4 Hybrid','XSE','suv','awd','hybrid','cvt','2.5L Hybrid',219,41,38,5,0,39900,41500,'Blueprint','The RAV4 Hybrid XSE delivers impressive AWD efficiency without compromise. Sport-tuned suspension and a bold design separate it from the standard RAV4 Hybrid.','["Toyota Safety Sense 2.5","AWD-i system","8-inch touchscreen","Sport suspension","Heated seats"]','["commuter","eco","family"]','["fuel-economy","safety","reliability"]',NULL,'Mountain Motors',1),

('suv-006','cpo',2021,'Toyota','Highlander','XLE','suv','awd','gasoline','automatic','3.5L V6',295,21,29,8,41200,38900,NULL,'Midnight Black','Toyota Certified Pre-Owned Highlander XLE. 8-seater with third row, V6 power, and full Toyota CPO warranty coverage. Inspected and ready.','["Toyota CPO Warranty","Third-row seating","Toyota Safety Sense 2.0","Power tailgate","Leather seating"]','["family","adventure"]','["safety","cargo","reliability"]',NULL,'Mountain Motors',1),

('truck-001','new',2024,'Ford','F-150','XLT','truck','4wd','gasoline','automatic','3.5L EcoBoost V6',400,18,24,6,0,52900,55200,'Iconic Silver','The F-150 XLT with the 3.5L EcoBoost is the best-selling truck in America for good reason — maximum towing, payload, and a refined interior. Built for work and weekend adventure.','["Pro Trailer Backup Assist","SYNC 4","FordPass Connect","Max Trailer Tow Package","Tailgate step"]','["commercial","adventure"]','["towing","reliability","cargo"]',NULL,'Summit Ford',1),

('truck-002','used',2022,'Chevrolet','Silverado 1500','LT','truck','4wd','gasoline','automatic','5.3L V8',355,15,21,6,29800,38500,NULL,'Summit White','Silverado LT with the 5.3L V8 — proven, capable, and ready for work. MultiPro tailgate, trailer tow package, and a clean one-owner history.','["5.3L V8 engine","MultiPro tailgate","Tow/haul mode","4WD Auto","Chevy Safety Assist"]','["commercial","adventure","family"]','["towing","cargo","reliability"]',NULL,'Mountain Motors',1),

('truck-003','used',2021,'Toyota','Tacoma','TRD Off-Road','truck','4wd','gasoline','automatic','3.5L V6',278,17,22,5,34200,34200,NULL,'Army Green','The Tacoma TRD Off-Road is legendary for a reason — Crawl Control, Terrain Select, and a locking rear diff make it a true off-road machine. Low miles, one owner.','["TRD Off-Road package","Crawl Control","Locking rear differential","Multi-terrain select","Toyota Safety Sense-P"]','["adventure","commercial"]','["reliability","towing","performance"]',NULL,'Mountain Motors',1),

('truck-004','new',2023,'Ford','Ranger','XLT','truck','4wd','gasoline','automatic','2.3L EcoBoost',270,20,26,5,0,39800,41200,'Carbonized Gray','The Ranger XLT is the right-sized truck — easier to park than a full-size but still capable of real towing and payload. FordPass and Co-Pilot360 included.','["Ford Co-Pilot360","FordPass Connect","2.3L EcoBoost","Class-III tow package","SYNC 4"]','["commercial","adventure","commuter"]','["towing","fuel-economy","tech"]',NULL,'Summit Ford',1),

('sedan-001','new',2023,'Toyota','Camry','XSE','sedan','fwd','gasoline','automatic','2.5L 4-cylinder',203,28,39,5,0,28500,29900,'Midnight Black','The Camry XSE V4 is sportier than it looks — adaptive suspension, sport-tuned steering, and a bold design. Toyota Safety Sense 3.0 is standard.','["Toyota Safety Sense 3.0","Sport-tuned suspension","9-inch touchscreen","Apple CarPlay / Android Auto","Wireless charging"]','["commuter","performance"]','["reliability","safety","fuel-economy"]',NULL,'Mountain Motors',1),

('sedan-002','used',2021,'Honda','Accord','Sport','sedan','fwd','gasoline','cvt','1.5L Turbo',192,30,38,5,31200,24900,NULL,'Sonic Gray Pearl','The Accord Sport is one of the best midsize sedans on the market. Sport trim adds 19-inch wheels, a sport exhaust, and a more aggressive look at a great used price.','["Honda Sensing","10.2-inch touchscreen","Heated front seats","Wireless CarPlay","Blind spot monitoring"]','["commuter","performance"]','["reliability","fuel-economy","tech"]',NULL,'Mountain Motors',1),

('sedan-003','used',2019,'Toyota','Corolla','LE','sedan','fwd','gasoline','cvt','1.8L 4-cylinder',139,30,38,5,52100,14500,NULL,'Classic Silver','Reliable, efficient, and affordable — the Corolla LE with Toyota Safety Sense-P and solid fuel economy. Perfect first car or budget daily driver.','["Toyota Safety Sense-P","Apple CarPlay","Backup camera","Lane departure alert","Automatic high beams"]','["commuter","eco"]','["fuel-economy","reliability","safety"]',NULL,'Mountain Motors',1),

('hatch-001','used',2022,'Mazda','Mazda3','Turbo AWD','hatchback','awd','gasoline','automatic','2.5L Turbo',250,23,31,5,18400,28800,NULL,'Polymetal Gray','The Mazda3 Turbo AWD hatchback is a sleeper — 250hp, AWD, and Mazda''s premium interior at a fraction of the luxury car price. One of the most fun-to-drive cars at any price.','["2.5L Turbo AWD","Bose 12-speaker audio","Heads-up display","i-Activsense safety suite","Heated seats"]','["performance","commuter"]','["performance","tech","fuel-economy"]',NULL,'Mountain Motors',1),

('hatch-002','new',2023,'Subaru','Impreza','Sport','hatchback','awd','gasoline','cvt','2.5L 4-cylinder',182,28,36,5,0,24200,25400,'Ice Silver','Standard AWD in a compact hatchback — the Impreza Sport is perfect for city driving in any weather. EyeSight and a spacious cargo area round out the package.','["Subaru EyeSight","Standard AWD","Apple CarPlay / Android Auto","Sport interior","Roof rails"]','["commuter","adventure","eco"]','["safety","reliability","fuel-economy"]',NULL,'Mountain Motors',1),

('van-001','used',2022,'Honda','Odyssey','EX-L','minivan','fwd','gasoline','automatic','3.5L V6',280,19,28,8,24100,34500,NULL,'Lunar Silver','The Odyssey EX-L is the family hauler benchmark — Magic Slide second row, CabinWatch camera, and CabinTalk intercom. Leather, heated seats, and Honda Sensing standard.','["Magic Slide second row","CabinWatch and CabinTalk","Honda Sensing","Heated leather seats","Wireless CarPlay"]','["family","commuter"]','["cargo","safety","tech"]',NULL,'Mountain Motors',1),

('van-002','new',2023,'Chrysler','Pacifica','Touring L','minivan','fwd','gasoline','automatic','3.6L V6',287,19,28,7,0,41900,43500,'Bright White','The Pacifica Touring L with Stow n Go seating — the ultimate family hauler. Uconnect 10.1-inch screen, FCA safety suite, and available 4G WiFi hotspot.','["Stow n Go seating","Uconnect 10.1-inch","FCA safety suite","Heated front seats","Rear entertainment ready"]','["family"]','["cargo","safety","tech"]',NULL,'Mountain Motors',1),

('coupe-001','used',2022,'Ford','Mustang','GT Premium','coupe','rwd','gasoline','automatic','5.0L V8',450,15,24,4,12400,38900,NULL,'Race Red','The Mustang GT Premium with the 5.0L Coyote V8 — pure American muscle. Low miles, premium package with leather, Brembo brakes, and active exhaust. This one is immaculate.','["5.0L Coyote V8","Brembo brakes","Active exhaust","Leather interior","SYNC 3 with 8-inch screen"]','["performance"]','["performance","luxury"]',NULL,'Summit Ford',1),

('coupe-002','new',2023,'Mazda','MX-5 Miata','Grand Touring','coupe','rwd','gasoline','automatic','2.0L 4-cylinder',181,26,34,2,0,32500,33900,'Soul Red Crystal','The MX-5 Miata Grand Touring is the purest driving experience available — 50/50 weight balance, Brembo brakes, and Recaro-style seats in a drop-top that makes every commute feel special.','["Retractable soft top","Brembo front brakes","Sport leather seats","Mazda Connect infotainment","Blind spot monitoring"]','["performance","commuter"]','["performance","fuel-economy"]',NULL,'Mountain Motors',1),

('ev-001','new',2023,'Ford','Mustang Mach-E','California Route 1','suv','awd','electric','automatic','Dual Motor Electric',480,NULL,NULL,5,0,52900,55000,'Vapor Blue','The Mach-E California Route 1 delivers extended range and all-wheel drive. Ford BlueCruise hands-free highway driving and the SYNC 4A 15.5-inch screen make this the electric SUV benchmark.','["Extended range battery","Ford BlueCruise","15.5-inch SYNC 4A screen","Dual motor AWD","DC Fast Charge capable"]','["commuter","eco","performance"]','["tech","fuel-economy","performance"]',NULL,'Summit Ford',1),

('ev-002','used',2022,'Toyota','RAV4 Prime','XSE','suv','awd','plug-in-hybrid','automatic','2.5L Plug-In Hybrid',302,94,40,5,18200,42500,NULL,'Supersonic Red','The RAV4 Prime XSE gets 42 miles of pure electric range for daily driving, then switches to hybrid for longer trips. AWD, 302hp, and Sports mode make it the best of all worlds.','["42-mile EV range","302hp combined output","AWD-i all-wheel drive","Sport and EV modes","Toyota Safety Sense 2.0"]','["eco","commuter","family"]','["fuel-economy","safety","performance"]',NULL,'Mountain Motors',1),

('ev-003','used',2023,'Tesla','Model 3','Long Range','sedan','awd','electric','automatic','Dual Motor Electric',358,NULL,NULL,5,14800,38900,NULL,'Pearl White','Low-mile Tesla Model 3 Long Range with Full Self-Driving capability. 358-mile range, supercharger access, and over-the-air updates keep it current. The benchmark EV sedan.','["358-mile range","Full Self-Driving hardware","Autopilot","15-inch touchscreen","Supercharger network access"]','["commuter","eco","performance"]','["tech","fuel-economy","reliability"]',NULL,'Mountain Motors',1),

('cpo-001','cpo',2022,'Ford','Edge','Titanium','suv','awd','gasoline','automatic','2.0L EcoBoost',250,22,29,5,28900,31500,NULL,'Magnetic Gray','Ford Certified Pre-Owned Edge Titanium. Full CPO inspection, extended warranty, and roadside assistance included. AWD, heated leather, panoramic roof, and SYNC 3.','["Ford CPO Warranty","Panoramic moonroof","Heated leather seats","SYNC 3","Co-Pilot360"]','["commuter","family"]','["safety","reliability","tech"]',NULL,'Summit Ford',1),

('cpo-002','cpo',2022,'Honda','Pilot','EX-L','suv','awd','gasoline','automatic','3.5L V6',280,20,27,8,32100,37500,NULL,'Sonic Gray Pearl','Honda Certified Pre-Owned Pilot EX-L. 8-passenger seating, third row, AWD, and the full Honda CPO program. Hands-free power tailgate and CabinControl app included.','["Honda CPO Warranty","Third-row seating","Honda Sensing","Hands-free tailgate","Heated leather seats"]','["family","adventure"]','["cargo","safety","reliability"]',NULL,'Mountain Motors',1),

('budget-001','used',2018,'Honda','Civic','LX','sedan','fwd','gasoline','cvt','1.5L Turbo',158,32,42,5,61200,12900,NULL,'Aegean Blue','A clean, fuel-efficient Civic LX — one of the most reliable cars on the road. Excellent fuel economy, Honda Sensing standard, and a remaining powertrain warranty.','["Honda Sensing","Apple CarPlay","Backup camera","Lane keeping assist","Automatic emergency braking"]','["commuter","eco"]','["fuel-economy","reliability","safety"]',NULL,'Mountain Motors',1),

('budget-002','used',2019,'Ford','Focus ST','ST','hatchback','fwd','gasoline','manual','2.0L EcoBoost',252,22,30,5,48200,17900,NULL,'Orange Fury','The Focus ST is a hot hatch legend — 252hp, a 6-speed manual, Recaro seats, and track-ready Brembo brakes. Rare, fun, and priced to move.','["2.0L EcoBoost 252hp","Recaro sport seats","Brembo brakes","6-speed manual","ST sport suspension"]','["performance","commuter"]','["performance","fuel-economy"]',NULL,'Summit Ford',1),

('suv-007','used',2020,'Toyota','4Runner','TRD Off-Road','suv','4wd','gasoline','automatic','4.0L V6',270,16,19,5,44100,39900,NULL,'Army Green','The 4Runner TRD Off-Road is built for serious capability. Body-on-frame construction, Multi-terrain Select, KDSS suspension, and a locking rear diff make it unstoppable off-road.','["KDSS suspension","Locking rear differential","Multi-terrain select","Kinetic Dynamic Suspension","Toyota Safety Sense-P"]','["adventure","commercial"]','["towing","reliability","performance"]',NULL,'Mountain Motors',1),

('suv-008','new',2024,'Chevrolet','Equinox EV','RS','suv','awd','electric','automatic','Dual Motor Electric',290,NULL,NULL,5,0,41900,43500,'Summit White','The all-new Equinox EV RS delivers 300+ miles of range, GM Super Cruise hands-free driving, and a striking design at a price that qualifies for the federal EV tax credit.','["300+ mile range","GM Super Cruise","17.7-inch diagonal infotainment","Wireless CarPlay","DC Fast Charge"]','["commuter","eco"]','["tech","fuel-economy","safety"]',NULL,'Mountain Motors',1);
